# -*- coding: utf-8 -*-
"""dqn_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FbyGH_f2lcQhwJpqp4bqTgOIy6zJpoiD

# DQN Training for Fire-Rescue Environment

#### Deep Q-Network - Value-Based Reinforcement Learning

This notebook includes:
 - 10+ hyperparameter configurations
 - Training with different settings
 - Logging and visualization
 - Model saving and evaluation
"""

#!pip install gymnasium stable-baselines3 tensorboard matplotlib pandas seaborn tqdm

import sys
import os
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import json
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')

from stable_baselines3 import DQN
from stable_baselines3.common.callbacks import EvalCallback, CheckpointCallback, CallbackList
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy

project_root = Path.cwd().parent if 'training' in str(Path.cwd()) else Path.cwd()
sys.path.insert(0, str(project_root))

from environment.custom_env import FireRescueEnv

SEED = 42
np.random.seed(SEED)

print("✓ All libraries imported successfully")
print(f"✓ Project root: {project_root}")

"""
Create necessary directories for models and logs
"""
base_dir = project_root / "models" / "dqn"
logs_dir = base_dir / "training_logs"
tensorboard_dir = base_dir / "tensorboard"
results_dir = project_root / "results"
plots_dir = results_dir / "plots"

for directory in [base_dir, logs_dir, tensorboard_dir, results_dir, plots_dir]:
    directory.mkdir(parents=True, exist_ok=True)

print("✓ Directories created:")
print(f"  - Models: {base_dir}")
print(f"  - Logs: {logs_dir}")
print(f"  - Tensorboard: {tensorboard_dir}")
print(f"  - Results: {results_dir}")

DQN_CONFIGS = {
    # ─────────────────────────────────────────────────────────────────────
    # Config 1: BASELINE
    # ─────────────────────────────────────────────────────────────────────
    "config_1_baseline": {
        "learning_rate": 1e-3,
        "gamma": 0.99,
        "batch_size": 32,
        "exploration_initial_eps": 1.0,
        "exploration_final_eps": 0.05,
        "exploration_fraction": 0.2,
        "buffer_size": 50000,
        "learning_starts": 1000,
        "tau": 1.0,
        "policy_kwargs": dict(net_arch=[64, 64]),
        "description": "Baseline - Standard settings"
    },

    # ─────────────────────────────────────────────────────────────────────
    # Config 2: HIGH LEARNING RATE
    # ─────────────────────────────────────────────────────────────────────
    "config_2_high_lr": {
        "learning_rate": 5e-3,
        "gamma": 0.99,
        "batch_size": 32,
        "exploration_initial_eps": 1.0,
        "exploration_final_eps": 0.05,
        "exploration_fraction": 0.2,
        "buffer_size": 50000,
        "learning_starts": 1000,
        "tau": 1.0,
        "policy_kwargs": dict(net_arch=[64, 64]),
        "description": "High LR - Fast learning"
    },

    # ─────────────────────────────────────────────────────────────────────
    # Config 3: LOW LEARNING RATE
    # ─────────────────────────────────────────────────────────────────────
    "config_3_low_lr": {
        "learning_rate": 1e-5,
        "gamma": 0.99,
        "batch_size": 32,
        "exploration_initial_eps": 1.0,
        "exploration_final_eps": 0.05,
        "exploration_fraction": 0.2,
        "buffer_size": 50000,
        "learning_starts": 1000,
        "tau": 1.0,
        "policy_kwargs": dict(net_arch=[64, 64]),
        "description": "Low LR - Careful learning"
    },

    # ─────────────────────────────────────────────────────────────────────
    # Config 4: LARGE BATCH
    # ─────────────────────────────────────────────────────────────────────
    "config_4_large_batch": {
        "learning_rate": 1e-3,
        "gamma": 0.99,
        "batch_size": 128,
        "exploration_initial_eps": 1.0,
        "exploration_final_eps": 0.05,
        "exploration_fraction": 0.2,
        "buffer_size": 50000,
        "learning_starts": 1000,
        "tau": 1.0,
        "policy_kwargs": dict(net_arch=[64, 64]),
        "description": "Large Batch - Stable gradients"
    },

    # ─────────────────────────────────────────────────────────────────────
    # Config 5: SMALL BATCH
    # ─────────────────────────────────────────────────────────────────────
    "config_5_small_batch": {
        "learning_rate": 1e-3,
        "gamma": 0.99,
        "batch_size": 16,
        "exploration_initial_eps": 1.0,
        "exploration_final_eps": 0.05,
        "exploration_fraction": 0.2,
        "buffer_size": 50000,
        "learning_starts": 1000,
        "tau": 1.0,
        "policy_kwargs": dict(net_arch=[64, 64]),
        "description": "Small Batch - Fast updates"
    },

    # ─────────────────────────────────────────────────────────────────────
    # Config 6: LOW GAMMA
    # ─────────────────────────────────────────────────────────────────────
    "config_6_low_gamma": {
        "learning_rate": 1e-3,
        "gamma": 0.95,
        "batch_size": 32,
        "exploration_initial_eps": 1.0,
        "exploration_final_eps": 0.05,
        "exploration_fraction": 0.2,
        "buffer_size": 50000,
        "learning_starts": 1000,
        "tau": 1.0,
        "policy_kwargs": dict(net_arch=[64, 64]),
        "description": "Low Gamma - Short-term focus"
    },

    # ─────────────────────────────────────────────────────────────────────
    # Config 7: HIGH GAMMA
    # ─────────────────────────────────────────────────────────────────────
    "config_7_high_gamma": {
        "learning_rate": 1e-3,
        "gamma": 0.995,
        "batch_size": 32,
        "exploration_initial_eps": 1.0,
        "exploration_final_eps": 0.05,
        "exploration_fraction": 0.2,
        "buffer_size": 50000,
        "learning_starts": 1000,
        "tau": 1.0,
        "policy_kwargs": dict(net_arch=[64, 64]),
        "description": "High Gamma - Long-term planning"
    },

    # ─────────────────────────────────────────────────────────────────────
    # Config 8: FAST EXPLORATION DECAY
    # ─────────────────────────────────────────────────────────────────────
    "config_8_fast_decay": {
        "learning_rate": 1e-3,
        "gamma": 0.99,
        "batch_size": 32,
        "exploration_initial_eps": 1.0,
        "exploration_final_eps": 0.1,
        "exploration_fraction": 0.1,
        "buffer_size": 50000,
        "learning_starts": 1000,
        "tau": 1.0,
        "policy_kwargs": dict(net_arch=[64, 64]),
        "description": "Fast Decay - Quick exploitation"
    },

    # ─────────────────────────────────────────────────────────────────────
    # Config 9: SLOW EXPLORATION DECAY
    # ─────────────────────────────────────────────────────────────────────
    "config_9_slow_decay": {
        "learning_rate": 1e-3,
        "gamma": 0.99,
        "batch_size": 32,
        "exploration_initial_eps": 1.0,
        "exploration_final_eps": 0.01,
        "exploration_fraction": 0.4,
        "buffer_size": 50000,
        "learning_starts": 1000,
        "tau": 1.0,
        "policy_kwargs": dict(net_arch=[64, 64]),
        "description": "Slow Decay - Extended exploration"
    },

    # ─────────────────────────────────────────────────────────────────────
    # Config 10: OPTIMIZED
    # ─────────────────────────────────────────────────────────────────────
    "config_10_optimized": {
        "learning_rate": 3e-4,
        "gamma": 0.99,
        "batch_size": 64,
        "exploration_initial_eps": 1.0,
        "exploration_final_eps": 0.02,
        "exploration_fraction": 0.3,
        "buffer_size": 50000,
        "learning_starts": 1000,
        "tau": 1.0,
        "policy_kwargs": dict(net_arch=[128, 128]),
        "description": "Optimized - Balanced settings"
    },

    # ─────────────────────────────────────────────────────────────────────
    # Config 11: NO EXPLORATION
    # ─────────────────────────────────────────────────────────────────────
    "config_11_no_exploration": {
        "learning_rate": 1e-3,
        "gamma": 0.95,
        "batch_size": 32,
        "exploration_initial_eps": 0,
        "exploration_final_eps": 0,
        "exploration_fraction": 0.2,
        "buffer_size": 50000,
        "learning_starts": 1000,
        "tau": 1.0,
        "policy_kwargs": dict(net_arch=[64, 64]),
        "description": "No Exploration - Pure exploitation"
    }
}

print(f"Training {len(DQN_CONFIGS)} DQN configurations\n")
print("=" * 100)
print(f"{'Config':<30} {'LR':<10} {'Gamma':<8} {'Batch':<8} {'ε_start':<10} {'ε_end':<10} {'ε_decay':<10}")
print("=" * 100)

for config_name, config in DQN_CONFIGS.items():
    print(f"{config_name:<30} {config['learning_rate']:<10.0e} {config['gamma']:<8.3f} "
          f"{config['batch_size']:<8} {config['exploration_initial_eps']:<10.2f} "
          f"{config['exploration_final_eps']:<10.2f} {config['exploration_fraction']:<10.2f}")

print("=" * 100)

"""## 🔥 CRITICAL BUG FIX - Scan Exploit

**Problem Identified:** The old model had 0% success rate because:
1. **Scan Exploit**: Scanning near survivor gave +0.5 reward
2. When agent **carries** survivor, it's always "near" the survivor  
3. Agent learned to **spam SCAN** instead of moving to door and dropping!

**Fix Applied:**
- ✅ Scan now gives **-0.2 penalty** when carrying survivor
- ✅ Scan only gives +0.5 reward when NOT carrying (for finding survivor)
- ✅ Added +0.5 bonus for being AT survivor location (encourages pickup)
- ✅ Added +1.0 bonus for being AT door while carrying (encourages drop)

**You MUST retrain** - the old model learned the exploit!
"""

"""
Set training parameters (matching PPO for fair comparison)

IMPORTANT: Environment now uses max_time=250 (updated from 200)
"""
# Training settings
TOTAL_TIMESTEPS = 100000
EVAL_FREQ = 5000
N_EVAL_EPISODES = 10
SAVE_FREQ = 10000

print("Training Configuration:")
print(f"  - Total Timesteps: {TOTAL_TIMESTEPS:,}")
print(f"  - Evaluation Frequency: {EVAL_FREQ:,}")
print(f"  - Evaluation Episodes: {N_EVAL_EPISODES}")
print(f"  - Checkpoint Frequency: {SAVE_FREQ:,}")
print(f"  - Environment max_time: 250 steps (updated from 200)")
print(f"\nNote: Timesteps match PPO training for fair comparison")

"""
Function to train a single DQN configuration
UPDATED: Uses max_time=250 for all environments
"""

def train_dqn_config(config_name, config, total_timesteps=TOTAL_TIMESTEPS):
    """
    Train DQN with given configuration

    Args:
        config_name: Name of the configuration
        config: Dictionary of hyperparameters
        total_timesteps: Total training steps

    Returns:
        Dictionary with training results
    """
    print(f"\n{'='*70}")
    print(f"Training: {config_name}")
    print(f"Description: {config['description']}")
    print(f"{'='*70}")

    env = FireRescueEnv(grid_size=10, max_time=250)
    env = Monitor(env)

    eval_env = FireRescueEnv(grid_size=10, max_time=250)
    eval_env = Monitor(eval_env)

    model_dir = base_dir / config_name
    model_dir.mkdir(exist_ok=True)

    eval_callback = EvalCallback(
        eval_env,
        best_model_save_path=str(model_dir),
        log_path=str(logs_dir / config_name),
        eval_freq=EVAL_FREQ,
        n_eval_episodes=N_EVAL_EPISODES,
        deterministic=True,
        render=False,
        verbose=1
    )

    checkpoint_callback = CheckpointCallback(
        save_freq=SAVE_FREQ,
        save_path=str(model_dir / "checkpoints"),
        name_prefix="dqn_checkpoint",
        save_replay_buffer=True,
        save_vecnormalize=True
    )

    callback_list = CallbackList([eval_callback, checkpoint_callback])

    train_config = {k: v for k, v in config.items() if k != 'description'}

    model = DQN(
        "MlpPolicy",
        env,
        verbose=1,
        seed=SEED,
        tensorboard_log=str(tensorboard_dir / config_name),
        **train_config
    )

    start_time = datetime.now()
    print(f"\nStarting training at {start_time.strftime('%H:%M:%S')}")

    try:
        model.learn(
            total_timesteps=total_timesteps,
            callback=callback_list,
            progress_bar=True
        )

        training_time = (datetime.now() - start_time).total_seconds()
        print(f"\n✓ Training completed in {training_time:.1f} seconds")

        final_model_path = model_dir / "final_model"
        model.save(str(final_model_path))
        print(f"✓ Model saved to {final_model_path}")

        print("\nFinal evaluation (100 episodes)...")
        mean_reward, std_reward = evaluate_policy(
            model,
            eval_env,
            n_eval_episodes=100,
            deterministic=True
        )


        print(f"Calculating episode performance metrics...")
        episode_rewards = []
        episode_lengths = []
        wall_collision_rates = []
        scan_efficiencies = []
        pickup_attempts_list = []
        time_to_find_survivor_list = []
        success_count = 0

        for episode_num in range(100):
            obs, _ = eval_env.reset()
            done = False

            while not done:
                action, _states = model.predict(obs, deterministic=True)
                obs, reward, terminated, truncated, info = eval_env.step(action)
                done = terminated or truncated

            episode_rewards.append(info.get('episode_length', 0) * -0.01)
            episode_lengths.append(info.get('episode_length', 0))
            wall_collision_rates.append(info.get('wall_collision_rate', 0))
            scan_efficiencies.append(info.get('scan_efficiency', 0))
            pickup_attempts_list.append(info.get('pickup_attempts', 0))

            if info.get('success', False):
                success_count += 1

            time_found = info.get('time_to_find_survivor', None)
            if time_found is not None:
                time_to_find_survivor_list.append(time_found)

            if episode_num < 5:
                success_str = "✓ SUCCESS" if info.get('success', False) else "✗ Failed"
                print(f"  Episode {episode_num+1}: {success_str} | "
                      f"Steps: {info.get('episode_length', 0)} | "
                      f"Wall Collisions: {info.get('wall_collision_rate', 0):.2%} | "
                      f"Scan Eff: {info.get('scan_efficiency', 0):.2%}")

        success_rate = success_count / 100
        print(f"\nEvaluation Summary:")
        print(f"   SUCCESS RATE: {success_rate:.1%} ({success_count}/100)")
        print(f"   Average Episode Length: {np.mean(episode_lengths):.1f} steps")
        print(f"   Wall Collision Rate: {np.mean(wall_collision_rates):.2%}")
        print(f"   Scan Efficiency: {np.mean(scan_efficiencies):.2%}")
        print(f"   Avg Pickup Attempts: {np.mean(pickup_attempts_list):.2f}")
        if time_to_find_survivor_list:
            print(f"   Avg Time to Find Survivor: {np.mean(time_to_find_survivor_list):.1f} steps ({len(time_to_find_survivor_list)}/100 found)")

        results = {
            'config_name': config_name,
            'description': config['description'],
            'mean_reward': mean_reward,
            'std_reward': std_reward,
            'success_rate': success_rate,
            'success_count': success_count,
            'avg_episode_length': np.mean(episode_lengths),
            'wall_collision_rate': np.mean(wall_collision_rates),
            'scan_efficiency': np.mean(scan_efficiencies),
            'avg_pickup_attempts': np.mean(pickup_attempts_list),
            'avg_time_to_find_survivor': float(np.mean(time_to_find_survivor_list)) if time_to_find_survivor_list else None,
            'survivor_found_count': len(time_to_find_survivor_list),
            'training_time': training_time,
            'total_timesteps': total_timesteps,
            'hyperparameters': train_config
        }

        results_file = model_dir / "results.json"
        with open(results_file, 'w') as f:
            json_results = {
                'config_name': config_name,
                'description': config['description'],
                'mean_reward': float(mean_reward),
                'std_reward': float(std_reward),
                'success_rate': float(success_rate),
                'success_count': success_count,
                'avg_episode_length': float(np.mean(episode_lengths)),
                'wall_collision_rate': float(np.mean(wall_collision_rates)),
                'scan_efficiency': float(np.mean(scan_efficiencies)),
                'avg_pickup_attempts': float(np.mean(pickup_attempts_list)),
                'avg_time_to_find_survivor': float(np.mean(time_to_find_survivor_list)) if time_to_find_survivor_list else None,
                'survivor_found_count': len(time_to_find_survivor_list),
                'training_time': float(training_time),
                'total_timesteps': total_timesteps,
                'hyperparameters': {
                    k: (float(v) if isinstance(v, (np.floating, np.integer)) else v)
                    for k, v in train_config.items() if k != 'policy_kwargs'
                }
            }
            json.dump(json_results, f, indent=4)

        print(f"✓ Results saved to {results_file}")

        env.close()
        eval_env.close()

        return results

    except Exception as e:
        print(f"\n✗ Training failed: {e}")
        env.close()
        eval_env.close()
        return None

print("✓ Training function defined")

"""
Train all DQN configurations
WARNING: This will take several hours!
"""

all_results = []

print(f"\n{'#'*70}")
print(f"STARTING FULL TRAINING RUN")
print(f"Training {len(DQN_CONFIGS)} configurations")
print(f"Estimated time: {len(DQN_CONFIGS) * 15} - {len(DQN_CONFIGS) * 30} minutes")
print(f"{'#'*70}\n")

for config_name, config in DQN_CONFIGS.items():
    results = train_dqn_config(config_name, config)

    if results:
        all_results.append(results)
        print(f"\n✓ Completed {len(all_results)}/{len(DQN_CONFIGS)} configurations")
    else:
        print(f"\n✗ Failed configuration: {config_name}")

    print(f"\n{'='*70}\n")

print(f"\n{'#'*70}")
print(f"TRAINING COMPLETE!")
print(f"Successfully trained: {len(all_results)}/{len(DQN_CONFIGS)} configurations")
print(f"{'#'*70}")

# ═══════════════════════════════════════════════════════════════════════
# CELL 8: Create Results DataFrame
# ═══════════════════════════════════════════════════════════════════════
"""
Organize results into a pandas DataFrame for analysis
"""

# Check if we have any results
if len(all_results) == 0:
    print("\n" + "="*70)
    print("NO SUCCESSFUL TRAINING RUNS")
    print("="*70)
    print("\nPossible issues:")
    print("1. Missing packages: Run 'pip install stable-baselines3[extra]'")
    print("2. Environment import error: Check environment/custom_env.py exists")
    print("3. GPU/memory issues: Try reducing TOTAL_TIMESTEPS in Cell 5")
    print("\nPlease fix the errors above and re-run Cell 7")
    print("="*70)
else:
    # Create DataFrame
    results_df = pd.DataFrame(all_results)

    # Display results (matching PPO format)
    print("\n" + "="*70)
    print("DQN TRAINING RESULTS SUMMARY")
    print("="*70)
    print(results_df[['config_name', 'mean_reward', 'std_reward', 'wall_collision_rate',
                      'scan_efficiency', 'avg_pickup_attempts', 'training_time']].to_string(index=False))

    # Save to CSV
    csv_path = results_dir / "dqn_results.csv"
    results_df.to_csv(csv_path, index=False)
    print(f"\n✓ Results saved to {csv_path}")

    # Find best configuration
    best_config = results_df.loc[results_df['mean_reward'].idxmax()]
    print(f"\n{'='*70}")
    print("BEST CONFIGURATION")
    print(f"{'='*70}")
    print(f"Name: {best_config['config_name']}")
    print(f"Description: {best_config['description']}")
    print(f"Mean Reward: {best_config['mean_reward']:.2f} ± {best_config['std_reward']:.2f}")
    print(f"Avg Episode Length: {best_config['avg_episode_length']:.1f} steps")
    print(f"Wall Collision Rate: {best_config['wall_collision_rate']:.2%}")
    print(f"Scan Efficiency: {best_config['scan_efficiency']:.2%}")
    print(f"Avg Pickup Attempts: {best_config['avg_pickup_attempts']:.2f}")
    if best_config['avg_time_to_find_survivor'] is not None:
        print(f"Time to Find Survivor: {best_config['avg_time_to_find_survivor']:.1f} steps")
    print(f"Training Time: {best_config['training_time']:.1f}s")

"""
Create comprehensive visualization of results (matching PPO format)
"""

# Set style
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (16, 12)

fig, axes = plt.subplots(2, 2, figsize=(16, 12))

# Sort by mean reward
results_sorted = results_df.sort_values('mean_reward', ascending=False)

# 1. Mean Reward Comparison
ax1 = axes[0, 0]
bars = ax1.barh(range(len(results_sorted)), results_sorted['mean_reward'],
                xerr=results_sorted['std_reward'], capsize=5)
ax1.set_yticks(range(len(results_sorted)))
ax1.set_yticklabels(results_sorted['config_name'], fontsize=9)
ax1.set_xlabel('Mean Reward', fontsize=12, fontweight='bold')
ax1.set_title('DQN Configuration Performance Comparison', fontsize=14, fontweight='bold')
ax1.axvline(x=0, color='red', linestyle='--', alpha=0.5)

# Color bars by performance
colors = plt.cm.RdYlGn(np.linspace(0.3, 0.9, len(bars)))
for bar, color in zip(bars, colors):
    bar.set_color(color)

ax1.grid(axis='x', alpha=0.3)

# 2. Scan Efficiency (matching PPO)
ax2 = axes[0, 1]
scan_eff_sorted = results_df.sort_values('scan_efficiency', ascending=False)
bars2 = ax2.barh(range(len(scan_eff_sorted)), scan_eff_sorted['scan_efficiency'] * 100)
ax2.set_yticks(range(len(scan_eff_sorted)))
ax2.set_yticklabels(scan_eff_sorted['config_name'], fontsize=9)
ax2.set_xlabel('Scan Efficiency (%)', fontsize=12, fontweight='bold')
ax2.set_title('Scan Efficiency by Configuration', fontsize=14, fontweight='bold')
ax2.grid(axis='x', alpha=0.3)

# Color bars
colors2 = plt.cm.RdYlGn(np.linspace(0.3, 0.9, len(bars2)))
for bar, color in zip(bars2, colors2):
    bar.set_color(color)

# 3. Training Time vs Performance
ax3 = axes[1, 0]
scatter = ax3.scatter(results_df['training_time'], results_df['mean_reward'],
                     s=results_df['scan_efficiency']*500, alpha=0.6,
                     c=results_df['mean_reward'], cmap='RdYlGn')
ax3.set_xlabel('Training Time (seconds)', fontsize=12, fontweight='bold')
ax3.set_ylabel('Mean Reward', fontsize=12, fontweight='bold')
ax3.set_title('Training Efficiency: Time vs Performance', fontsize=14, fontweight='bold')
ax3.grid(alpha=0.3)

# Add labels for best and worst
best_idx = results_df['mean_reward'].idxmax()
worst_idx = results_df['mean_reward'].idxmin()
ax3.annotate('Best', xy=(results_df.loc[best_idx, 'training_time'],
                         results_df.loc[best_idx, 'mean_reward']),
            xytext=(10, 10), textcoords='offset points',
            bbox=dict(boxstyle='round,pad=0.5', fc='green', alpha=0.3),
            arrowprops=dict(arrowstyle='->', connectionstyle='arc3,rad=0'))

# Colorbar
plt.colorbar(scatter, ax=ax3, label='Mean Reward')

# 4. Wall Collision Rate (matching PPO)
ax4 = axes[1, 1]
wall_coll_sorted = results_df.sort_values('wall_collision_rate', ascending=True)
bars4 = ax4.barh(range(len(wall_coll_sorted)), wall_coll_sorted['wall_collision_rate'] * 100)
ax4.set_yticks(range(len(wall_coll_sorted)))
ax4.set_yticklabels(wall_coll_sorted['config_name'], fontsize=9)
ax4.set_xlabel('Wall Collision Rate (%)', fontsize=12, fontweight='bold')
ax4.set_title('Wall Collision Rate by Configuration', fontsize=14, fontweight='bold')
ax4.grid(axis='x', alpha=0.3)

# Color bars (lower is better, so reverse colors)
colors4 = plt.cm.RdYlGn_r(np.linspace(0.3, 0.9, len(bars4)))
for bar, color in zip(bars4, colors4):
    bar.set_color(color)

plt.tight_layout()
plot_path = plots_dir / "dqn_comparison.png"
plt.savefig(plot_path, dpi=300, bbox_inches='tight')
print(f"\n✓ Comparison plot saved to {plot_path}")
plt.show()

"""
Detailed analysis of top 3 performing configurations (matching PPO format)
"""

print("\n" + "="*70)
print("TOP 3 CONFIGURATIONS - DETAILED ANALYSIS")
print("="*70)

top3 = results_df.nlargest(3, 'mean_reward')

for idx, (_, config) in enumerate(top3.iterrows(), 1):
    print(f"\n{'─'*70}")
    print(f"#{idx}: {config['config_name']}")
    print(f"{'─'*70}")
    print(f"Description: {config['description']}")
    print(f"Mean Reward: {config['mean_reward']:.2f} ± {config['std_reward']:.2f}")
    print(f"Avg Episode Length: {config['avg_episode_length']:.1f} steps")
    print(f"Wall Collision Rate: {config['wall_collision_rate']:.2%}")
    print(f"Scan Efficiency: {config['scan_efficiency']:.2%}")
    print(f"Avg Pickup Attempts: {config['avg_pickup_attempts']:.2f}")
    if config['avg_time_to_find_survivor'] is not None:
        print(f"Avg Time to Find Survivor: {config['avg_time_to_find_survivor']:.1f} steps")
    print(f"Survivor Found Count: {config['survivor_found_count']}/100")
    print(f"Training Time: {config['training_time']:.1f} seconds")

    if 'hyperparameters' in config and config['hyperparameters']:
        print(f"\nKey Hyperparameters:")
        hparams = config['hyperparameters']
        print(f"  - Learning Rate: {hparams.get('learning_rate', 'N/A')}")
        print(f"  - Batch Size: {hparams.get('batch_size', 'N/A')}")
        print(f"  - Buffer Size: {hparams.get('buffer_size', 'N/A')}")
        print(f"  - Gamma: {hparams.get('gamma', 'N/A')}")
        print(f"  - Exploration Fraction: {hparams.get('exploration_fraction', 'N/A')}")

"""
Create summary tables and statistics for the final report (matching PPO format)
"""

summary = {
    'total_configs': len(all_results),
    'best_config': best_config['config_name'],
    'best_mean_reward': float(best_config['mean_reward']),
    'best_scan_efficiency': float(best_config['scan_efficiency']),
    'best_wall_collision_rate': float(best_config['wall_collision_rate']),
    'avg_mean_reward': float(results_df['mean_reward'].mean()),
    'std_mean_reward': float(results_df['mean_reward'].std()),
    'avg_scan_efficiency': float(results_df['scan_efficiency'].mean()),
    'avg_wall_collision_rate': float(results_df['wall_collision_rate'].mean()),
    'total_training_time': float(results_df['training_time'].sum()),
}

summary_path = results_dir / "dqn_summary.json"
with open(summary_path, 'w') as f:
    json.dump(summary, f, indent=4)

print("\n" + "="*70)
print("DQN TRAINING SUMMARY")
print("="*70)
for key, value in summary.items():
    if 'rate' in key or 'efficiency' in key:
        if isinstance(value, float) and value < 1:
            print(f"{key.replace('_', ' ').title()}: {value:.2%}")
        else:
            print(f"{key.replace('_', ' ').title()}: {value}")
    else:
        print(f"{key.replace('_', ' ').title()}: {value}")

print(f"\n✓ Summary saved to {summary_path}")